//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ContactBook.Db.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class CB_Book_GroupTypes
    {
        public int GroupRelationId { get; set; }
        public long BookId { get; set; }
        public Nullable<int> GroupId { get; set; }
    
        public virtual CB_ContactBook CB_ContactBook { get; set; }
        public virtual CB_Group CB_Group { get; set; }
    }
}
