//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ContactBook.Db.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class CB_EmailType
    {
        public CB_EmailType()
        {
            this.CB_Emails = new HashSet<CB_Email>();
        }
    
        public int EmailTypeId { get; set; }
        public string Email_TypeName { get; set; }
        public Nullable<long> BookId { get; set; }
    
        public virtual ICollection<CB_Email> CB_Emails { get; set; }
        public virtual CB_ContactBook CB_ContactBook { get; set; }
    }
}
