//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ContactBook.Db.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class CB_IMType
    {
        public CB_IMType()
        {
            this.CB_IMs = new HashSet<CB_IM>();
        }
    
        public int IMTypeId { get; set; }
        public string IM_TypeName { get; set; }
        public string IMLogoPath { get; set; }
        public Nullable<long> BookId { get; set; }
    
        public virtual ICollection<CB_IM> CB_IMs { get; set; }
        public virtual CB_ContactBook CB_ContactBook { get; set; }
    }
}
