//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ContactBook.Db.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class CB_IM
    {
        public int IMId { get; set; }
        public string Username { get; set; }
        public long BookId { get; set; }
        public Nullable<int> IMTypeId { get; set; }
    
        public virtual CB_ContactBook CB_ContactBook { get; set; }
        public virtual CB_IMType CB_IMType { get; set; }
    }
}
