//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ContactBook.Db.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class CB_Number
    {
        public int NumberId { get; set; }
        public long ContactId { get; set; }
        public string Number { get; set; }
        public Nullable<int> NumberTypeId { get; set; }
    
        public virtual CB_Contact CB_Contacts { get; set; }
        public virtual CB_NumberType CB_NumberType { get; set; }
    }
}
