//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ContactBook.Db.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class CB_RelationshipType
    {
        public CB_RelationshipType()
        {
            this.Relationship_TypeCode = "C";
            this.CB_Relationships = new HashSet<CB_Relationship>();
        }
    
        public int RelationshipTypeId { get; set; }
        public string UserId { get; set; }
        public string Relationship_TypeName { get; set; }
        public string Relationship_TypeCode { get; set; }
    
        public virtual ICollection<CB_Relationship> CB_Relationships { get; set; }
    }
}
