//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ContactBook.Db.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class CB_Suffix
    {
        public CB_Suffix()
        {
            this.CB_ContactBooks = new HashSet<CB_ContactBook>();
        }
    
        public int SuffixId { get; set; }
        public string Suffix { get; set; }
    
        public virtual ICollection<CB_ContactBook> CB_ContactBooks { get; set; }
    }
}
