//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ContactBook.Db.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class CB_SpecialDateType
    {
        public CB_SpecialDateType()
        {
            this.CB_SpecialDates = new HashSet<CB_SpecialDates>();
        }
    
        public int SpecialDateTpId { get; set; }
        public string Date_TypeName { get; set; }
        public Nullable<long> BookId { get; set; }
    
        public virtual ICollection<CB_SpecialDates> CB_SpecialDates { get; set; }
        public virtual CB_ContactBook CB_ContactBook { get; set; }
    }
}
