//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ContactBook.Db.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Log
    {
        public System.Guid LogId { get; set; }
        public string Logger { get; set; }
        public string LoggerLevel { get; set; }
        public string CallSite { get; set; }
        public string Message { get; set; }
        public System.TimeSpan TimeStamp { get; set; }
    }
}
