//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ContactBook.Db
{
    using System;
    using System.Collections.Generic;
    
    public partial class CB_AddressType
    {
        public CB_AddressType()
        {
            this.Address_TypeCode = "C";
            this.CB_Address = new HashSet<CB_Address>();
        }
    
        public int AddressTypeId { get; set; }
        public string UserId { get; set; }
        public string Address_TypeName { get; set; }
        public string Address_TypeCode { get; set; }
    
        public virtual ICollection<CB_Address> CB_Address { get; set; }
    }
}
