//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ContactBook.Db
{
    using System;
    using System.Collections.Generic;
    
    public partial class CB_EmailType
    {
        public CB_EmailType()
        {
            this.Email_TypeCode = "C";
            this.CB_Emails = new HashSet<CB_Email>();
        }
    
        public int EmailTypeId { get; set; }
        public string UserId { get; set; }
        public string Email_TypeName { get; set; }
        public string Email_TypeCode { get; set; }
    
        public virtual ICollection<CB_Email> CB_Emails { get; set; }
    }
}
