//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ContactBook.Db
{
    using System;
    using System.Collections.Generic;
    
    public partial class CB_NumberType
    {
        public CB_NumberType()
        {
            this.Number_TypeCode = "C";
            this.CB_Numbers = new HashSet<CB_Number>();
        }
    
        public int NumberTypeId { get; set; }
        public string UserId { get; set; }
        public string Number_TypeName { get; set; }
        public string Number_TypeCode { get; set; }
    
        public virtual ICollection<CB_Number> CB_Numbers { get; set; }
    }
}
