//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ContactBook.Db
{
    using System;
    using System.Collections.Generic;
    
    public partial class CB_SpecialDates
    {
        public int SpecialDateId { get; set; }
        public long BookId { get; set; }
        public System.DateTime Dates { get; set; }
        public int SpecialDateTpId { get; set; }
    
        public virtual CB_ContactBook CB_ContactBook { get; set; }
        public virtual CB_SpecialDateType CB_SpecialDateType { get; set; }
    }
}
