//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ContactBook.Db
{
    using System;
    using System.Collections.Generic;
    
    public partial class ContactAddress
    {
        public int AddressId { get; set; }
        public long BookId { get; set; }
        public string Address { get; set; }
        public Nullable<int> Dflt_AddressTypeId { get; set; }
        public Nullable<int> Cst_AddressTypeId { get; set; }
    
        public virtual ContactBook ContactBook { get; set; }
        public virtual Default_AddressType Default_AddressType { get; set; }
        public virtual Custom_AddressType Custom_AddressType { get; set; }
    }
}
