//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ContactBook.Db
{
    using System;
    using System.Collections.Generic;
    
    public partial class ContactBook_GroupTypes
    {
        public int GroupRelationId { get; set; }
        public long BookId { get; set; }
        public Nullable<int> Cst_GroupId { get; set; }
        public Nullable<int> Dflt_GroupId { get; set; }
    
        public virtual ContactBook ContactBook { get; set; }
        public virtual Custom_ContactGroup ContactGroup { get; set; }
        public virtual Default_GroupType DefaultGroupType { get; set; }
    }
}
