//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ContactBook.Db
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ContactBookEdmContainer : DbContext
    {
        public ContactBookEdmContainer()
            : base("name=ContactBookEdmContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<ContactBook> ContactBooks { get; set; }
        public DbSet<ContactNumber> ContactNumbers { get; set; }
        public DbSet<ContactEmail> ContactEmails { get; set; }
        public DbSet<ContactAddress> ContactAddresses { get; set; }
        public DbSet<Custom_ContactGroup> Custom_ContactGroup { get; set; }
        public DbSet<Default_GroupType> Default_GroupType { get; set; }
        public DbSet<Custom_NumberType> Custom_NumberType { get; set; }
        public DbSet<Default_NumberType> Default_NumberType { get; set; }
        public DbSet<ContactBook_GroupTypes> ContactBook_GroupTypes { get; set; }
        public DbSet<Custom_AddressType> Custom_AddressType { get; set; }
        public DbSet<Default_AddressType> Default_AddressType { get; set; }
        public DbSet<Custom_EmailType> Custom_EmailType { get; set; }
        public DbSet<Default_EmailType> Default_EmailType { get; set; }
        public DbSet<Default_Suffix> Default_Suffix { get; set; }
        public DbSet<IM> IMs { get; set; }
        public DbSet<Default_IMType> Default_IMType { get; set; }
        public DbSet<Custom_IMType> Custom_IMType { get; set; }
        public DbSet<ContactWebsite> ContactWebsites { get; set; }
        public DbSet<ContactRelationship> ContactRelationships { get; set; }
        public DbSet<Default_RelationshipType> Default_RelationshipType { get; set; }
        public DbSet<Custom_RelationshipType> Custom_RelationshipType { get; set; }
        public DbSet<ContactSpecialDates> ContactSpecialDates { get; set; }
        public DbSet<Default_SpecialDateType> Default_SpecialDateType { get; set; }
        public DbSet<Custom_SpecialDateType> Custom_SpecialDateType { get; set; }
        public DbSet<ContactInternetCall> ContactInternetCalls { get; set; }
    }
}
