//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ContactBook.Db
{
    using System;
    using System.Collections.Generic;
    
    public partial class ContactSpecialDates
    {
        public int SpecialDataeId { get; set; }
        public long BookId { get; set; }
        public System.DateTime Dates { get; set; }
        public Nullable<int> Dflt_SpecialDateTpId { get; set; }
        public int Cst_SpecialDateTpId { get; set; }
    
        public virtual ContactBook ContactBook { get; set; }
        public virtual Default_SpecialDateType Default_SpecialDateType { get; set; }
        public virtual Custom_SpecialDateType Custom_SpecialDateType { get; set; }
    }
}
