//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ContactBook.Db
{
    using System;
    using System.Collections.Generic;
    
    public partial class ContactNumber
    {
        public int NumberId { get; set; }
        public long BookId { get; set; }
        public string Number { get; set; }
        public Nullable<int> Dflt_NumberTypeId { get; set; }
        public Nullable<int> NumberTypeId { get; set; }
    
        public virtual ContactBook ContactBook { get; set; }
        public virtual Default_NumberType Default_NumberType { get; set; }
        public virtual Custom_NumberType Custom_NumberType { get; set; }
    }
}
