//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ContactBook.Db
{
    using System;
    using System.Collections.Generic;
    
    public partial class ContactBook
    {
        public ContactBook()
        {
            this.ContactNumbers = new HashSet<ContactNumber>();
            this.ContactEmails = new HashSet<ContactEmail>();
            this.ContactBookAndGroups = new HashSet<ContactBook_GroupTypes>();
            this.ContactAddresses = new HashSet<ContactAddress>();
            this.IMs = new HashSet<IM>();
            this.ContactWebsites = new HashSet<ContactWebsite>();
            this.ContactRelationships = new HashSet<ContactRelationship>();
            this.ContactSpecialDates = new HashSet<ContactSpecialDates>();
            this.ContactInternetCalls = new HashSet<ContactInternetCall>();
        }
    
        public long BookId { get; set; }
        public string UserId { get; set; }
        public string Firstname { get; set; }
        public string Lastname { get; set; }
        public string Middlename { get; set; }
        public Nullable<int> SuffixId { get; set; }
        public string PhFirstname { get; set; }
        public string PhMiddlename { get; set; }
        public string PhSurname { get; set; }
        public string CompanyName { get; set; }
        public string JobTitle { get; set; }
        public string Notes { get; set; }
        public string NickName { get; set; }
    
        public virtual ICollection<ContactNumber> ContactNumbers { get; set; }
        public virtual ICollection<ContactEmail> ContactEmails { get; set; }
        public virtual ICollection<ContactBook_GroupTypes> ContactBookAndGroups { get; set; }
        public virtual ICollection<ContactAddress> ContactAddresses { get; set; }
        public virtual Default_Suffix Default_Suffix { get; set; }
        public virtual ICollection<IM> IMs { get; set; }
        public virtual ICollection<ContactWebsite> ContactWebsites { get; set; }
        public virtual ICollection<ContactRelationship> ContactRelationships { get; set; }
        public virtual ICollection<ContactSpecialDates> ContactSpecialDates { get; set; }
        public virtual ICollection<ContactInternetCall> ContactInternetCalls { get; set; }
    }
}
