//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ContactBook.Db
{
    using System;
    using System.Collections.Generic;
    
    public partial class ContactEmail
    {
        public int EmailId { get; set; }
        public long BookId { get; set; }
        public string Email { get; set; }
        public Nullable<int> Cst_EmailTypeId { get; set; }
        public Nullable<int> Dflt_EmailTypeId { get; set; }
    
        public virtual ContactBook ContactBook { get; set; }
        public virtual Custom_EmailType Custom_EmailType { get; set; }
        public virtual Default_EmailType Default_EmailType { get; set; }
    }
}
