//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ContactBook.Db
{
    using System;
    using System.Collections.Generic;
    
    public partial class ContactRelationship
    {
        public int RelationshipId { get; set; }
        public long BookId { get; set; }
        public Nullable<int> Dflt_RelationshipTypeId { get; set; }
        public Nullable<int> Cst_RelationshipTypeId { get; set; }
    
        public virtual ContactBook ContactBook { get; set; }
        public virtual Default_RelationshipType Default_RelationshipType { get; set; }
        public virtual Custom_RelationshipType Custom_RelationshipType { get; set; }
    }
}
