//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ContactBook.Db
{
    using System;
    using System.Collections.Generic;
    
    public partial class Custom_EmailType
    {
        public Custom_EmailType()
        {
            this.ContactEmails = new HashSet<ContactEmail>();
        }
    
        public int Cst_EmailTypeId { get; set; }
        public string EmailType { get; set; }
    
        public virtual ICollection<ContactEmail> ContactEmails { get; set; }
    }
}
