//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ContactBook.Db
{
    using System;
    using System.Collections.Generic;
    
    public partial class Custom_SpecialDateType
    {
        public Custom_SpecialDateType()
        {
            this.ContactSpecialDates = new HashSet<ContactSpecialDates>();
        }
    
        public int Cst_SpecialDateTpId { get; set; }
        public string DateType { get; set; }
    
        public virtual ICollection<ContactSpecialDates> ContactSpecialDates { get; set; }
    }
}
