//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ContactBook.Db
{
    using System;
    using System.Collections.Generic;
    
    public partial class Default_IMType
    {
        public Default_IMType()
        {
            this.IMs = new HashSet<IM>();
        }
    
        public int Dflt_IMTypeId { get; set; }
        public string IMName { get; set; }
        public string IMLogoPath { get; set; }
    
        public virtual ICollection<IM> IMs { get; set; }
    }
}
