//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ContactBook.Db
{
    using System;
    using System.Collections.Generic;
    
    public partial class Default_RelationshipType
    {
        public Default_RelationshipType()
        {
            this.ContactRelationships = new HashSet<ContactRelationship>();
        }
    
        public int Dflt_RelationshipTypeId { get; set; }
        public string RelationName { get; set; }
    
        public virtual ICollection<ContactRelationship> ContactRelationships { get; set; }
    }
}
