//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ContactBook.Db
{
    using System;
    using System.Collections.Generic;
    
    public partial class Default_GroupType
    {
        public Default_GroupType()
        {
            this.ContactBookAndGroups = new HashSet<ContactBook_GroupTypes>();
        }
    
        public int Dflt_GroupId { get; set; }
        public string GroupName { get; set; }
    
        public virtual ICollection<ContactBook_GroupTypes> ContactBookAndGroups { get; set; }
    }
}
