//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ContactBook.Db
{
    using System;
    using System.Collections.Generic;
    
    public partial class Default_Suffix
    {
        public Default_Suffix()
        {
            this.ContactBooks = new HashSet<ContactBook>();
        }
    
        public int SuffixId { get; set; }
        public string Suffix { get; set; }
    
        public virtual ICollection<ContactBook> ContactBooks { get; set; }
    }
}
