//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ContactBook.Db
{
    using System;
    using System.Collections.Generic;
    
    public partial class Default_AddressType
    {
        public Default_AddressType()
        {
            this.ContactAddresses = new HashSet<ContactAddress>();
        }
    
        public int Dflt_AddressTypeId { get; set; }
        public string AddressType { get; set; }
    
        public virtual ICollection<ContactAddress> ContactAddresses { get; set; }
    }
}
