//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ContactBook.Db
{
    using System;
    using System.Collections.Generic;
    
    public partial class Default_NumberType
    {
        public Default_NumberType()
        {
            this.ContactNumbers = new HashSet<ContactNumber>();
        }
    
        public int Dflt_NumberTypeId { get; set; }
        public string NumberType { get; set; }
    
        public virtual ICollection<ContactNumber> ContactNumbers { get; set; }
    }
}
