//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ContactBook.Db
{
    using System;
    using System.Collections.Generic;
    
    public partial class IM
    {
        public int IMId { get; set; }
        public string Username { get; set; }
        public long BookId { get; set; }
        public Nullable<int> Dflt_IMTypeId { get; set; }
        public Nullable<int> Cst_IMTypeId { get; set; }
    
        public virtual ContactBook ContactBook { get; set; }
        public virtual Default_IMType Default_IMType { get; set; }
        public virtual Custom_IMType Custom_IMType { get; set; }
    }
}
